name: EPG Service

on:
  schedule:
    - cron: "30 3 * * *" # every day at 3:30am UTC (9:00am IST)
#     - cron:  '45 16 * * *' # test

jobs:
  epg:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests xmltodict
      - name: Get EPG Data
        run: |
          python ./tv/epg.py ./tv/epg.xml
          tar -czvf epg.xml.gz epg.xml
      - name: Commit updated epg.xml
        run: |
          git config --global user.name 'botallen'
          git config --global user.email 'botallen@users.noreply.github.com'
          git commit -am "Automated EPG"
          git push
